---
- import_tasks: hostname.yml
- import_tasks: ../../tasks/apt.yml
- include_tasks: ../../tasks/user.yml
  vars:
    username: '{{ ansible_user }}'
    userid: '{{ ansible_userid }}'
    pwless_sudo: true
- include_tasks: ../../tasks/user.yml
  vars:
    username: '{{ main_network_user }}'
    userid: '{{ main_network_user_userid }}'
    pwless_sudo: true
- import_tasks: root_user.yml
- import_tasks: ssh.yml
- import_tasks: network_online_flag_service.yml
- import_tasks: locales.yml
- import_tasks: motd.yml
