---
- name: update and upgrade packages (including autoremove)
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    autoremove: true
    upgrade: full
  tags:
    - apt
    - install

- name: install essential packages
  become: true
  ansible.builtin.package:
    name: '{{ packages }}'
    state: latest
  when:
    - packages is defined
    - packages | length > 0
  tags:
    - apt
    - install
