---
- name: prep vars
  ansible.builtin.set_fact:
    volumes_flat: '{{ service_pod.containers | default([]) | subelements("volumes", skip_missing=True) }}'
    # if is_file is true, take dirname; otherwise use full path

- name: prep cartesian product
  ansible.builtin.set_fact:
    # create cartesian product: each volume combined with [true, false]
    cartesian_product: '{{ volumes_flat | product([true, false]) | list }}'

- name: 'create directories for user {{ username }}'
  become: true
  ansible.builtin.file:
    path: '{{ resolved_path }}'
    state: directory
    mode: '0755'
    owner: '{{ username }}'
    group: '{{ username }}'
  loop: '{{ volumes_flat }}'
  loop_control:
    loop_var: volume
  vars:
    resolved_path: >-
      {%- set raw_path = volume.1.host | replace('%h', '/home/' ~ username) -%}
      {{ (volume.1.is_file | default(false)) | ternary(raw_path | dirname , raw_path) }}
  when: >
    volume.1.host is match('^/') or
    volume.1.host is match('^%h/')
  tags: [install]

- name: 'assign default and current ACL for directories outside of /home/{{ username }}'
  become: true
  ansible.posix.acl:
    # if is_file is true, take dirname; otherwise use full path
    path: '{{ resolved_path }}'
    entity: '{{ username }}'
    etype: user
    permissions: '{{ volume.1.permissions }}'
    state: present
    recurse: yes
    default: '{{ acl_type }}'
  loop: '{{ cartesian_product }}'
  loop_control:
    loop_var: loop_item
  vars:
    resolved_path: >-
      {%- set raw_path = volume.1.host | replace('%h', '/home/' ~ username) -%}
      {{ (volume.1.is_file | default(false)) | ternary(raw_path | dirname , raw_path) }}
    volume: '{{ loop_item.0 }}'
    acl_type: '{{ loop_item.1 }}'
  when: >
    volume.1.permissions is defined and
    (
      volume.1.host is match('^/') or
      volume.1.host is match('^%h/')
    )
  tags: [install]

