---
- name: 'remove nfs mount quadlets'
  become: true
  ansible.builtin.file:
    path: '/etc/systemd/system/{{ unit_filename }}'
    state: absent
  loop: '{{ service_pod.nfs_mounts }}'
  loop_control:
    loop_var: nfs_mount
  vars:
    full_mount_path: '{{ [mount_base | replace("%h", "/home/" ~ username), nfs_mount.name] | ansible.builtin.path_join }}'
    unit_filename: '{{ full_mount_path | regex_replace("^/", "") | replace("/", "-")  }}.mount'
  when: service_pod.nfs_mounts is defined
  tags: [never,uninstall]

