---
- name: 'remove passwordless sudo for user {{ username }}'
  become: true
  community.general.sudoers:
    name: '{{ username }}-noPW'
    user: '{{ username }}'
    commands: ALL
    runas: ALL
    nopassword: true
    state: absent
  when: pwless_sudo | default(false) | bool
  tags: [uninstall,never]

- name: 'check linger status for user {{ username }}'
  become: true
  ansible.builtin.stat:
    path: '/var/lib/systemd/linger/{{ username }}'
  register: linger_result
  changed_when: false

- name: 'disable linger for user {{ username }}'
  become: true
  ansible.builtin.command: 'loginctl disable-linger {{ username }}'
  when: linger_result.stat.exists
  tags: [uninstall,never]

- name: 'update ssh host config with user {{ username }}'
  become: false
  ansible.builtin.blockinfile:
    path: '/home/{{ ansible_user }}/{{ inventory_hostname }}_ssh_host_config'
    marker: '# {mark} ANSIBLE MANAGED BLOCK for {{ username }} on {{ inventory_hostname }}'
    block: |
      Host {{ username }}_on_{{ inventory_hostname }}
        HostName {{ ansible_host }}
        User {{ username }}
      IdentityFile {{ ssh_key }}
    create: yes
    mode: '0644'
    state: absent
  register: host_config_block
  tags: [uninstall,never]

- name: 'fetch generated ssh host config to localhost'
  become: false
  ansible.builtin.fetch:
    src: '/home/{{ ansible_user }}/{{ inventory_hostname }}_ssh_host_config'
    dest: '~/.ssh/config.d/'
    flat: true
  when: host_config_block.changed
  tags: [uninstall,never]

- name: 'remove {{ username }} from control-node mounters.catalog'
  become: false
  ansible.builtin.lineinfile:
    path: '{{ playbook_dir }}/artifacts/EXPORTS/mounters.catalog'
    regexp: '^{{ username }}'
    line: '{{ username }}: absent'
  delegate_to: localhost
  when: service_pod.nfs_mounts is defined
  tags: [uninstall,never]

- name: 'remove {{ username }} from {{ inventory_hostname }}'
  become: true
  ansible.builtin.user:
    name: '{{ username }}'
    state: absent
    remove: true
  tags: [never,uninstall]

