#####################
# PERSONAL SETTINGS #
#####################

environment_TZ: Europe/Berlin

main_network_user: pip

ssh_key: '~/.ssh/my_homelab_key'
ssh_pubkey: '{{ ssh_key }}.pub'

shell: 'zsh'
shell_path: '/bin/zsh'
shell_config_filename: 'zshrc'
shell_dot_repo: https://github.com/pipboy20k/zshrc
shell_dot_files: '/home/{{ username }}/.config/zsh'


############
# USER IDs #
############

main_network_user_userid: 1000
ansible_userid:           1001

mounters_group_id:        1066
# network stuff
#unifi_controller_userid:  1101


# smart home stuff
#homeassistant_userid:     1200
#z2m_userid:               1201
#mosquitto_userid:         1202

# media and other stuff
#audiobookshelf_userid:    1301
#jellyfin_userid:          1302
#airsonic_userid:          1303
#navidrome:                1304
#paperless_userid:         1305
#kavita_userid:            1306
#papertest_userid:         1399

userid: '{{ lookup("vars", username ~ "_userid") }}'


#################
# PUBLISH PORTS #
#################

# network stuff
#unifi_controller_port:    8101

# smart_home_stuff
#homeassistant_port:       8200
#z2m_port:                 8201
#mosquitto_port:           8202

# media and other stuff
#audiobookshelf_port:      8301
#jellyfin_port:            8302
#airsonic_port:            8303
#navidrome:                8304
#paperless_port:           8305
#paperless_sftp_port:      2222


####################
# GENERAL SETTINGS #
####################

container_path: '/home/{{ username }}/.config/containers/systemd/'
become_env:
  XDG_RUNTIME_DIR: '/run/user/{{ userid }}'
  DBUS_SESSION_BUS_ADDRESS: 'unix:path=/run/user/{{ userid }}/bus'
