username: USERNAME
pwless_sudo: false # OPTIONAL
servicename: NameOfThePod

mount_base: '%h/nfs_mounts/'

# for now, the tasks are designed with *EITHER* a service_pod *OR* one or more virtual machines per role. Behaviour if both are defined is untested (and will probably remain so)

service_pod:
  name: '{servicename}'
  description: 'what this service does'
  publish_ports:
    - host: '{{ lookup("vars", username ~ "_port") }}'
      container: '8000'
      bind_ip: '127.0.0.1' # OPTIONAL and probably UNUSUAL, this way, only the host interface with the ip 127.0.0.1 can access the published port
  named_volumes:
    - name: 'myVolume'
  nfs_mounts:
    - name: 'audiobooks'
      src: '192.168.0.1:/path/to/audiobooks'
      options: 'rw,sync,_netdev,nofail,hard,timeo=600,retrans=3'
    - name: 'podcasts_shelf'
      src: '192.168.0.1:/path/to/podcasts_shelf'
      options: 'rw,sync,_netdev,nofail,hard,timeo=600,retrans=3'

  containers:
    - name: 'someName'
      description: 'what this container is for within the pod'
      image: 'docker.io/library/redis'
      tag: '8'
      volumes: # OPTIONAL
        - host: 'myVolume.volume'
          container: '/usr/src/paperless/consume'
          flags: 'U,z' # OPTIONAL
        - host: '/mnt/media'
          container: '/media'
          permissions: 'rwx' # OPTIONAL
          flags: 'z' # OPTIONAL
      environment_variables: # OPTIONAL
        - key: 'SOME_OPTION'
          value: 'the_setting'
      capabilities: # OPTIONAL
        - 'NET-ADMIN'

#virtual_machines:
#  - name: 'homeassistant'
#    image_version: '17.0'
#    image_suffix: 'qcow2'
#    image_archive_suffix: 'xz' # for now, only xz archives are supported, see ansible_root_folder/tasks/load_vm_image.yml
#    image_name: 'haos_ova-{{ image_version }}.{{ image_suffix }}'
#    image_online_src: 'https://github.com/home-assistant/operating-system/releases/download/{{ image_version }}/{{ image_name }}.{{ image_archive_suffix }}'
#    image_local_path: '/home/{{ username }}'
#    vm_mac_address: 'ba:54:00:aa:aa:bb'
#    vm_ram_KiB: 4194304
#    vm_vcpu_count: 2
#    vm_description: 'Home Assistant OS'
#    vm_xml_file: 'haos-vm.xml'

