motd_file: '000_base_config.txt'
packages:
  - podman
  - cockpit
  - cockpit-podman
  - crun
  - htop
  - btop
  - zsh
  - git
  - vim
  - neovim
  - hyfetch
  - acl
  - locales
  - python3-cryptography # for generating ssh keys with a specific private_key_format
  - jq
