---
- import_tasks: ../../tasks/apt_update_and_install.yml
- import_tasks: ../../tasks/setup_user.yml
- import_tasks: ../../tasks/create_directories.yml
- import_tasks: ../../tasks/create_quadlets.yml
#- import_tasks: ../../tasks/load_vm_image.yml
#- import_tasks: ../../tasks/setup_vm.yml
- import_tasks: ../../tasks/create_motd.yml
